# Generated by Django 4.2.6 on 2024-02-09 12:36

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("first_name", models.CharField(max_length=128, verbose_name="Имя")),
                (
                    "second_name",
                    models.CharField(max_length=128, verbose_name="Фамилия"),
                ),
                (
                    "fam_name",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="Отчество"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=128, unique=True, verbose_name="Email"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="Пароль")),
                (
                    "is_manager",
                    models.BooleanField(default=False, verbose_name="Менеджер"),
                ),
                (
                    "post",
                    models.CharField(
                        choices=[
                            ("JR", "Junior developer"),
                            ("MD", "Middle developer"),
                            ("SR", "Senior developer"),
                            ("TL", "Team lead"),
                            ("PM", "Project manager"),
                        ],
                        max_length=128,
                        verbose_name="Должность",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Сотрудники",
                "ordering": ("first_name",),
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=128, verbose_name="Название")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Описание"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата создания"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель проекта",
                    ),
                ),
                (
                    "employee",
                    models.ManyToManyField(
                        related_name="project_as_employee",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сотрудник проекта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=128, verbose_name="Название")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Описание"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата создания"),
                ),
                ("deadline", models.DateTimeField(verbose_name="Дата окончания")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Lowset", "Очень низкий"),
                            ("Low", "Низкий"),
                            ("Medium", "Средний"),
                            ("High", "Важный"),
                            ("Highest", "Срочный"),
                        ],
                        max_length=128,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Bug", "Баг"),
                            ("Task", "Задача"),
                            ("Epic", "Epic"),
                            ("Refactor", "Рефакторинг"),
                        ],
                        max_length=128,
                        verbose_name="Тип задачи",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TO DO", "Созданo"),
                            ("Stopped", "Приостановлено"),
                            ("In progress", "В работе"),
                            ("Review", "На ревью"),
                            ("In testing", "В тестировании"),
                            ("Complete", "Выполнено"),
                        ],
                        max_length=128,
                        verbose_name="Статус задачи",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teamwork.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "ordering": ("project",),
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Описание"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата создания"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор комментария",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teamwork.task",
                        verbose_name="Задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
                "ordering": ("task",),
            },
        ),
    ]
